package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	_ "github.com/JSYoo5B/convertago" // Register the messenger-owned profiles.
	"github.com/JSYoo5B/convertago/internal/conversion"
)

const modulePath = "github.com/JSYoo5B/convertago"
const generatedHeader = "// Code generated by convertago. DO NOT EDIT.\n"

var platforms = []string{"kakaowork", "slack", "googlechat"}

// Run analyzes the selected package and atomically writes generated accessors.
func Run(dir string, names []string, output string) error {
	if filepath.Base(output) != output || !strings.HasSuffix(output, ".go") || strings.HasSuffix(output, "_test.go") {
		return fmt.Errorf("convertago: output must be a Go filename in the source package")
	}
	target := filepath.Join(dir, output)
	if info, err := os.Lstat(target); err == nil {
		if !info.Mode().IsRegular() {
			return fmt.Errorf("convertago: output must be a regular file")
		}
		data, err := os.ReadFile(target)
		if err != nil {
			return err
		}
		if !bytes.HasPrefix(data, []byte(generatedHeader)) {
			return fmt.Errorf("convertago: refusing to overwrite non-generated file %s", output)
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	pkg, err := loadPackage(dir, output)
	if err != nil {
		return err
	}
	g := generator{pkg: pkg, imports: make(map[string]string)}
	if pkg.Path() != modulePath {
		g.imports[modulePath] = "_convertago"
		g.prefix = "_convertago."
	}
	seen := make(map[string]bool)
	for _, name := range names {
		name = strings.TrimSpace(name)
		if seen[name] {
			return fmt.Errorf("convertago: duplicate type %q", name)
		}
		seen[name] = true
		object, ok := pkg.Scope().Lookup(name).(*types.TypeName)
		if !ok || object.IsAlias() {
			return fmt.Errorf("convertago: %q must name a defined struct type", name)
		}
		named := object.Type().(*types.Named)
		if _, ok := named.Underlying().(*types.Struct); !ok || named.TypeParams().Len() != 0 {
			return fmt.Errorf("convertago: %q must be a non-generic struct type", name)
		}
		for i := 0; i < named.NumMethods(); i++ {
			if named.Method(i).Name() == "ConvertagoFields" {
				return fmt.Errorf("convertago: %s already declares ConvertagoFields", name)
			}
		}
		if err := g.root(named); err != nil {
			return err
		}
	}
	var file bytes.Buffer
	file.WriteString(generatedHeader)
	fmt.Fprintf(&file, "\npackage %s\n\nimport (\n", pkg.Name())
	var paths []string
	for path := range g.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		fmt.Fprintf(&file, "%s %q\n", g.imports[path], path)
	}
	file.WriteString(")\n\n")
	file.Write(g.body.Bytes())
	data, err := format.Source(file.Bytes())
	if err != nil {
		return fmt.Errorf("convertago: format generated source: %w", err)
	}
	temporary, err := os.CreateTemp(dir, ".convertago-*.tmp")
	if err != nil {
		return err
	}
	defer os.Remove(temporary.Name())
	if _, err := temporary.Write(data); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Chmod(0644); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporary.Name(), target)
}

type generator struct {
	pkg     *types.Package
	prefix  string
	imports map[string]string
	body    bytes.Buffer
}

func (g *generator) qualify(pkg *types.Package) string {
	if pkg == g.pkg {
		return ""
	}
	if alias := g.imports[pkg.Path()]; alias != "" {
		return alias
	}
	alias := fmt.Sprintf("_pkg%d", len(g.imports))
	g.imports[pkg.Path()] = alias
	return alias
}

func (g *generator) std(path string) string {
	if alias := g.imports[path]; alias != "" {
		return alias
	}
	alias := "_" + path
	g.imports[path] = alias
	return alias
}

func (g *generator) typeName(t types.Type) string { return types.TypeString(t, g.qualify) }

func (g *generator) root(t *types.Named) error {
	name := t.Obj().Name()
	fmt.Fprintf(&g.body, "// ConvertagoFields reads %s's tagged fields without reflection.\n", name)
	fmt.Fprintf(&g.body, "func (value %s) ConvertagoFields(platform string) ([]%sSourceField, error) {\nswitch platform {\n", name, g.prefix)
	var readers []*reader
	for _, platform := range platforms {
		profile, err := conversion.Lookup(platform)
		if err != nil {
			return err
		}
		shape := objectShape(t, profile)
		if err := conversion.ValidateShape(profile, shape); err != nil {
			return err
		}
		r := &reader{g: g, profile: profile, prefix: "convertago" + name + "_" + platform, memo: make(map[types.Type]string)}
		helper := r.helper(t)
		r.helpers[0].object = true
		delete(r.memo, t)
		fmt.Fprintf(&g.body, "case %q:\nreturn %s(value, &%sSourceState{}).Fields, nil\n", platform, helper, g.prefix)
		readers = append(readers, r)
	}
	fmt.Fprintf(&g.body, "default:\nreturn nil, %s.Errorf(\"convertago: unknown platform %%q\", platform)\n}\n}\n\n", g.std("fmt"))
	for _, r := range readers {
		for i := 0; i < len(r.helpers); i++ {
			r.emit(r.helpers[i])
		}
	}
	return nil
}

type helper struct {
	typeOf types.Type
	name   string
	object bool
}

type reader struct {
	g       *generator
	profile conversion.Profile
	prefix  string
	memo    map[types.Type]string
	helpers []helper
}

func (r *reader) helper(t types.Type) string {
	if name := r.memo[t]; name != "" {
		return name
	}
	name := fmt.Sprintf("%s_%d", r.prefix, len(r.helpers))
	r.memo[t] = name
	r.helpers = append(r.helpers, helper{typeOf: t, name: name})
	return name
}

func (r *reader) emit(h helper) {
	g, out := r.g, &r.g.body
	prefix := g.prefix
	t := h.typeOf
	underlying := t.Underlying()
	if object, ok := underlying.(*types.Struct); ok && (h.object || (!types.Implements(t, marshalerInterface) && !types.Implements(t, stringerInterface))) {
		for i := 0; i < object.NumFields(); i++ {
			tag, _ := conversion.Parse(r.profile, structTag(object.Tag(i), r.profile.Platform))
			if len(tag.Style) != 0 {
				fmt.Fprintf(out, "var %s_styles_%d = [...]string{\n", h.name, i)
				for _, style := range tag.Style {
					fmt.Fprintf(out, "%q,\n", style)
				}
				out.WriteString("}\n\n")
			}
			if len(tag.Fixed) != 0 {
				fmt.Fprintf(out, "var %s_fixed_%d = [...]%sSourceFixed{\n", h.name, i, prefix)
				for _, fixed := range tag.Fixed {
					fmt.Fprintf(out, "{Slot: %q, Value: %q},\n", fixed.Slot, fixed.Value)
				}
				out.WriteString("}\n\n")
			}
		}
	}
	fmt.Fprintf(out, "func %s(value %s, state *%sSourceState) %sSourceValue {\n", h.name, g.typeName(t), prefix, prefix)
	if _, ok := underlying.(*types.Interface); ok {
		fmt.Fprintf(out, "return state.Dynamic(value, %q)\n}\n\n", r.profile.Platform)
		return
	}
	_, pointer := underlying.(*types.Pointer)
	_, slice := underlying.(*types.Slice)
	_, mapType := underlying.(*types.Map)
	_, chanType := underlying.(*types.Chan)
	_, funcType := underlying.(*types.Signature)
	if pointer || slice || mapType || chanType || funcType {
		fmt.Fprintf(out, "if value == nil { return %sSourceValue{Kind: %q, Nil: true, Empty: true} }\n", prefix, kindOf(t))
	}
	if pointer {
		r.guard("value", "pointer")
	} else if slice {
		out.WriteString("if len(value) != 0 {\n")
		r.guard("&value[0]", "slice")
		out.WriteString("}\n")
	}
	if !h.object && types.Implements(t, marshalerInterface) {
		fmt.Fprintf(out, "result := %sSourceMarshaled(value)\n", prefix)
		if pointer {
			out.WriteString("result.Empty = false\n")
		}
		out.WriteString("return result\n}\n\n")
		return
	}
	if !h.object && types.Implements(t, stringerInterface) {
		out.WriteString("text := value.String()\n")
		empty := "text == \"\""
		if pointer {
			empty = "false"
		}
		fmt.Fprintf(out, "return %sSourceValue{Kind: \"scalar\", Text: text, Empty: %s}\n}\n\n", prefix, empty)
		return
	}
	switch underlying := underlying.(type) {
	case *types.Pointer:
		fmt.Fprintf(out, "result := %s(*value, state)\nresult.Empty = false\nreturn result\n", r.helper(underlying.Elem()))
	case *types.Struct:
		fmt.Fprintf(out, "return %sSourceObject([]%sSourceField{\n", prefix, prefix)
		for i := 0; i < underlying.NumFields(); i++ {
			field := underlying.Field(i)
			tag, _ := conversion.Parse(r.profile, structTag(underlying.Tag(i), r.profile.Platform))
			if tag.Role == "" {
				continue
			}
			styles := fmt.Sprintf("%s_styles_%d[:]", h.name, i)
			fixed := fmt.Sprintf("%s_fixed_%d[:]", h.name, i)
			fmt.Fprintf(out, "{Name: %q, Tag: %s, Value: %s(value.%s, state)},\n", field.Name(), tagLiteral(prefix, tag, styles, fixed), r.helper(field.Type()), field.Name())
		}
		out.WriteString("})\n")
	case *types.Slice:
		r.list(underlying.Elem())
	case *types.Array:
		r.list(underlying.Elem())
	case *types.Basic:
		text, empty := "", "value == 0"
		switch {
		case underlying.Info()&types.IsString != 0:
			text, empty = "string(value)", "len(value) == 0"
		case underlying.Info()&types.IsBoolean != 0:
			text, empty = g.std("strconv")+".FormatBool(bool(value))", "!bool(value)"
		case underlying.Info()&types.IsInteger != 0:
			if underlying.Info()&types.IsUnsigned != 0 {
				text = g.std("strconv") + ".FormatUint(uint64(value), 10)"
			} else {
				text = g.std("strconv") + ".FormatInt(int64(value), 10)"
			}
		case underlying.Info()&types.IsFloat != 0:
			bits := 64
			if underlying.Kind() == types.Float32 {
				bits = 32
			}
			text = fmt.Sprintf("%s.FormatFloat(float64(value), 'g', -1, %d)", g.std("strconv"), bits)
		}
		fmt.Fprintf(out, "return %sSourceValue{Kind: \"scalar\", Text: %s, Empty: %s}\n", prefix, text, empty)
	}
	out.WriteString("}\n\n")
}

func (r *reader) guard(pointer, kind string) {
	out := &r.g.body
	fmt.Fprintf(out, "if !state.Enter(%s, %q) { return %sSourceValue{Err: %s.Errorf(\"cyclic source value\")} }\ndefer state.Leave(%s, %q)\n", pointer, kind, r.g.prefix, r.g.std("fmt"), pointer, kind)
}

func (r *reader) list(elem types.Type) {
	out := &r.g.body
	fmt.Fprintf(out, "items := make([]%sSourceValue, len(value))\nfor i := range value { items[i] = %s(value[i], state) }\nreturn %sSourceValue{Kind: \"list\", Items: items, Empty: len(value) == 0}\n", r.g.prefix, r.helper(elem), r.g.prefix)
}

func tagLiteral(prefix string, tag conversion.Tag, styles, fixed string) string {
	pieces := []string{"Role: " + strconv.Quote(tag.Role)}
	for _, option := range []struct{ name, value string }{{"Group", tag.Group}, {"Slot", tag.Slot}, {"Format", tag.Format}} {
		if option.value != "" {
			pieces = append(pieces, option.name+": "+strconv.Quote(option.value))
		}
	}
	if len(tag.Style) != 0 {
		pieces = append(pieces, "Style: "+styles)
	}
	if tag.OmitEmpty {
		pieces = append(pieces, "OmitEmpty: true")
	}
	if tag.Optional {
		pieces = append(pieces, "Optional: true")
	}
	if len(tag.Fixed) != 0 {
		pieces = append(pieces, "Fixed: "+fixed)
	}
	return prefix + "SourceTag{" + strings.Join(pieces, ", ") + "}"
}

func kindOf(t types.Type) string {
	return sourceKind(t, make(map[types.Type]bool))
}

func sourceKind(t types.Type, seen map[types.Type]bool) string {
	if seen[t] {
		return "pointer"
	}
	seen[t] = true
	if _, ok := t.Underlying().(*types.Interface); ok {
		return "dynamic"
	}
	if types.Implements(t, marshalerInterface) || types.Implements(t, stringerInterface) {
		return "scalar"
	}
	switch underlying := t.Underlying().(type) {
	case *types.Pointer:
		return sourceKind(underlying.Elem(), seen)
	case *types.Struct:
		return "object"
	case *types.Slice, *types.Array:
		return "list"
	default:
		return "scalar"
	}
}

func textInterface(name string, results ...types.Type) *types.Interface {
	var variables []*types.Var
	for _, t := range results {
		variables = append(variables, types.NewVar(token.NoPos, nil, "", t))
	}
	signature := types.NewSignatureType(nil, nil, nil, types.NewTuple(), types.NewTuple(variables...), false)
	return types.NewInterfaceType([]*types.Func{types.NewFunc(token.NoPos, nil, name, signature)}, nil).Complete()
}

var marshalerInterface = textInterface("MarshalText", types.NewSlice(types.Typ[types.Byte]), types.Universe.Lookup("error").Type())
var stringerInterface = textInterface("String", types.Typ[types.String])
